export const propsForDatagrid = [
  {
    props: "data",
    type: "Array",
    default: "[]",
    description: "Les données à afficher dans le tableau",
    required: true,
  },
  {
    props: "columns",
    type: "Array",
    default: "[]",
    description: "Les headers du tableau",
    required: true,
  },
  {
    props: "loading",
    type: "boolean",
    default: "false",
    description: "Pendants le chargement des données mettre un spinner",
    required: false,
  },
  {
    props: "selectedColonne",
    type: "function",
    default: "",
    description: "Fonction qui permet de récupérer la colonne sélectionnée",
    required: true,
  },
  {
    props: "sortByAcs",
    type: "boolean",
    default: "false",
    description: "Permet de trier par acsendant",
    required: true,
  },
  {
    props: "setSortByAcs",
    type: "function",
    default: "",
    description:
      "Fonction qui permet de récupérer le tri par le boolean sortByAcs",
    required: true,
  },
  {
    props: "selected",
    type: "string",
    default: "",
    description: "Nom de la ligne sélectionnée",
    required: true,
  },
  {
    props: "paginate",
    type: "number",
    default: "",
    description: "Page actuelle",
    required: true,
  },
  {
    props: "setPaginate",
    type: "function",
    default: "",
    description: "Fonction qui permet de récupérer la page actuelle",
    required: true,
  },
  {
    props: "total",
    type: "number",
    default: "",
    description: "Nombre de pages",
    required: true,
  },
  {
    props: "size",
    type: "string",
    default: "md",
    description: "Taille du tableau",
    required: false,
  },
  {
    props: "colonneFontSize",
    type: "string",
    default: "xs",
    description: "Taille de la police des colonnes",
    required: false,
  },
  {
    props: "colonneTitleFontSize",
    type: "string",
    default: "sm",
    description: "Taille de la police des headers",
    required: false,
  },
  {
    props: "borderHeaderWidth",
    type: "string",
    default: "",
    description: "Taille de la bordure des headers",
    required: false,
  },
  {
    props: "borderColonneWidth",
    type: "string",
    default: "",
    description: "Taille de la bordure des colonnes",
    required: false,
  },
  {
    props: "variant",
    type: "string",
    default: "striped",
    description: "Variant du tableau",
    required: false,
  },
  {
    props: "backgroundBoxColor",
    type: "string",
    default: "",
    description: "Couleur de fond du tableau",
    required: false,
  },
  {
    props: "borderBoxColor",
    type: "string",
    default: "",
    description: "Couleur de la bordure du tableau",
    required: false,
  },
  {
    props: "borderBoxWidth",
    type: "string",
    default: "",
    description: "Taille de la bordure du tableau",
    required: false,
  },
  {
    props: "TheadBackgroundColor",
    type: "string",
    default: "white",
    description: "Couleur de fond du header",
    required: false,
  },
  {
    props: "boxRounded",
    type: "string",
    default: "",
    description: "Arrondi du tableau",
    required: false,
  },
  {
    props: "boxSize",
    type: "string",
    default: "16px",
    description: "Taille des icones sort ",
    required: false,
  },
]
