export const AcsDatagrid = [
  {
    name: "data",
    type: "Array",
    default: "[]",
    description: "Les données à afficher dans le tableau",
    required: true,
  },
  {
    name: "columns",
    type: "Array",
    default: "[]",
    description: "Les headers du tableau",
    required: true,
  },
  {
    name: "loading",
    type: "boolean",
    default: "false",
    description: "Pendants le chargement des données mettre un spinner",
    required: false,
  },
  {
    name: "selectedColonne",
    type: "function",
    default: "",
    description: "Fonction qui permet de récupérer la colonne sélectionnée",
    required: true,
  },
  {
    name: "sortByAcs",
    type: "boolean",
    default: "false",
    description: "Permet de trier par acsendant",
    required: true,
  },
  {
    name: "setSortByAcs",
    type: "function",
    default: "",
    description:
      "Fonction qui permet de récupérer le tri par le boolean sortByAcs",
    required: true,
  },
  {
    name: "selected",
    type: "string",
    default: "",
    description: "Nom de la ligne sélectionnée",
    required: true,
  },
  {
    name: "paginate",
    type: "number",
    default: "",
    description: "Page actuelle",
    required: true,
  },
  {
    name: "setPaginate",
    type: "function",
    default: "",
    description: "Fonction qui permet de récupérer la page actuelle",
    required: true,
  },
  {
    name: "total",
    type: "number",
    default: "",
    description: "Nombre de pages",
    required: true,
  },
  {
    name: "size",
    type: "string",
    default: "md",
    description: "Taille du tableau",
    required: false,
  },
  {
    name: "colonneFontSize",
    type: "string",
    default: "xs",
    description: "Taille de la police des colonnes",
    required: false,
  },
  {
    name: "colonneTitleFontSize",
    type: "string",
    default: "sm",
    description: "Taille de la police des headers",
    required: false,
  },
  {
    name: "borderHeaderWith",
    type: "string",
    default: "",
    description: "Taille de la bordure des headers",
    required: false,
  },
  {
    name: "borderColonneWith",
    type: "string",
    default: "",
    description: "Taille de la bordure des colonnes",
    required: false,
  },
  {
    name: "variant",
    type: "string",
    default: "striped",
    description: "Variant du tableau",
    required: false,
  },
]
