export const propsForDrawer = [
  {
    props: "title",
    type: "string",
    description: "Titre du drawer",
    required: false,
  },
  {
    props: "header",
    type: "JSX.Element",
    description: "Contenu du header",
    required: false,
  },
  {
    props: "body",
    type: "JSX.Element",
    description: "Contenu du body",
    required: true,
  },
  {
    props: "footer",
    type: "JSX.Element",
    description: "Contenu du footer",
    required: false,
  },
  {
    props: "isOpen",
    type: "boolean",
    description: "Ouverture du drawer",
    required: true,
  },
  {
    props: "onClose",
    type: "function",
    description: "Fonction qui ferme la drawer",
    required: true,
  },
  {
    props: "hasCloseBtn",
    type: "boolean",
    description: "Affichage du bouton de fermeture",
    required: false,
  },
  {
    props: "placement",
    type: "string",
    default: "right",
    description: "Position du drawer",
    required: false,
  },
  {
    props: "closeOnOverlayClick",
    type: "boolean",
    description: "Fermeture du drawer au clic sur l'overlay",
    required: false,
  },
  {
    props: "size",
    type: "string",
    default: "md",
    description: "Taille du drawer",
    required: false,
  },
  {
    props: "isLoading",
    type: "boolean",
    default: "false",
    description: "Affichage du loader",
    required: false,
  },
  {
    props: "colorSpinner",
    type: "string",
    default: "primary.500",
    description: "Couleur du loader",
    required: false,
  },
]
